---
title: "Metadata from ENB"
output:
  pdf_document:
    latex_engine: xelatex
  html_document:
    df_print: paged
    self_contained: no
editor_options:
  chunk_output_type: console
---

# Overview of the dataset

Last data file 08-10-2024, last updated processing 08-10-2024.

```{r setup,echo=F}
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())
```


```{r}



library(data.table)
library(tidyverse)
library(nanoparquet)
library(stringdist)

works_parq <- nanoparquet::read_parquet("~/Downloads/erb_all_books.parquet")
works <-  setDT(works_parq)

places_harmonized <- fread("data/authority_input_place_harmonized.tsv",sep="\t")

works4 <- merge(works,places_harmonized,by.x="publication_place",by.y="place_original",all.x=T)


works4[,publisher_orig:=publisher]
#works[,koht:=publication_place]
#und and & are often parts of publisher names
#works4[,publisher_orig:=str_replace(publisher_orig, " u\\. ", " ; ")]
#works4[,publisher_orig:=str_replace(publisher_orig, " und ", " ; ")]
#works4[,publisher_orig:=str_replace(publisher_orig, " & ", " ; ")]
#comma is sometimes within the name
#works4[,publisher_orig:=str_replace(publisher_orig, ",", ";")]
#str_replace("London [etc.]", " \\[etc\\.\\]", "")
works4[,publisher_orig:=str_replace(publisher_orig, ", levitaja", "")]

unlist_publishers <- works4[,.(publisher_unlist=unlist(str_split(publisher_orig,";"))),id][,publisher_unlist:=trimws(publisher_unlist)]

#6597 books have 2 or more publishers
unlist_publishers[,.(.N,publisher_unlist),id][N>1][,uniqueN(id)]


#fuzzy=T
works5 <- merge(works4,unlist_publishers, by="id")
## new harmonize.
#works <- fread(cmd="unzip -p data/ENB_works.tsv.zip",sep="\t")
#works[,kirjastus_orig:=str_replace_all(kirjastus_orig,'""+','"')]
#publishers <- unique(works[,.(publisher_orig=kirjastus_orig,aeg)][,n_orig:=.N,publisher_orig][n_orig>10,big_pub:=T][,min_time:=min(aeg,na.rm=T),publisher_orig][,max_time:=max(aeg,na.rm=T),publisher_orig][order(publisher_orig,-n_orig)][publisher_orig!=""][,-c("aeg")])
#works4[,publisher_unlist:=str_replace_all(publisher_unlist,'""+','"')]
publishers <- unique(works5[,.N,.(publisher_unlist,publication_date_cleaned,place_harmonized)][,n_works:=sum(N,na.rm=T),publisher_unlist][,years_publisher:=.N,publisher_unlist][years_publisher>10,big_pub:=T][,min_time:=min(publication_date_cleaned,na.rm=T),publisher_unlist][,max_time:=max(publication_date_cleaned,na.rm=T),publisher_unlist][order(publisher_unlist,-years_publisher)][publisher_unlist!=""][,-c("publication_date_cleaned","N")])

?amatch
stringdist("Treufeldt",list(publishers[str_detect(publisher_unlist,"Treufeldt"),publisher_unlist][1]),method="jw")
#J. Treufeldt Kuressaare
#J. Treufeldt & A. Kallus Kuressaare
#J. Treufeldt ja A. Kallus Kuressaare
#J. Treufeldt ja A. Kallus Kuresaare [i.e. Kuressaare
#J. Treufeldt'i & Kallus'e tr체kk Kuressaare
try <- publishers[str_detect(publisher_unlist,"Treufeldt"),CJ(V1=publisher_unlist,V2=publisher_unlist)][,dist:=stringdist(V1,V2,method="jw")]

#with person-names, small errors can be just different initial, which still makes it a different publisher.



publishers[,standardizing_name:=publisher_unlist]
publishers[,standardizing_name:=str_replace_all(standardizing_name,'""+','"')]
publishers[,standardizing_name:=str_replace_all(standardizing_name,",","")]
publishers[,standardizing_name:=str_replace_all(standardizing_name,"-","")]
publishers[,standardizing_name:=str_remove(standardizing_name,'^"+')]
publishers[,standardizing_name:=str_remove(standardizing_name,'"+$')]
publishers[,standardizing_name:=trimws(standardizing_name)]
publishers[,standardizing_name:=tolower(standardizing_name)]
publishers[,standardizing_name:=str_replace_all(standardizing_name,"\\. ",".")]
publishers[,standardizing_name:=str_replace_all(standardizing_name,"'i rmtkpl. ","")]
publishers[str_detect(standardizing_name,"\\["),standardizing_name:=str_replace_all(standardizing_name,"\\[","")]
publishers[str_detect(standardizing_name,"\\]"),standardizing_name:=str_replace_all(standardizing_name,"\\]","")]
publishers[,standardizing_name:=str_replace(standardizing_name,":$","")]
publishers[,standardizing_name:=str_replace(standardizing_name,";$","")]
publishers[,standardizing_name:=trimws(standardizing_name)]

rules <- fread("data/harmonize_publisher_rules.tsv",sep="\t",strip.white=F,quote="")
rules[,find_this:=str_replace(find_this,"\\\\","\\")]

rules[type=="exact"][,uniqueN(find_this)]
merged <- merge(publishers,rules[type=="exact"],by.x="standardizing_name",by.y="find_this",all.x=T)
merged[type=="exact",standardizing_name:=replace_with]
#12459 sellega veidi paremaks

regexes <- rules[type=="regex_replace"]
#merged[str_detect(standardizing_name,"noor eesti")]
#i <- 273
#merged[str_detect(standardizing_name,regexes[i,find_this])]
for (i in 1:nrow(regexes)){
  merged[str_detect(standardizing_name,regexes[i,find_this]),replace_with:=regexes[i,replace_with]]
  merged[str_detect(standardizing_name,regexes[i,find_this]),type:="regex_replace"]
  merged[!is.na(replace_with),standardizing_name:=replace_with]
  merged[,standardizing_name:=trimws(standardizing_name)]
}
regexes_partial <- rules[type=="regex_partial"]
#merged[str_detect(standardizing_name,"noor eesti")]
#i <- 45
#merged[str_detect(standardizing_name,regexes[i,find_this])]
for (i in 1:nrow(regexes_partial)){
  merged[str_detect(standardizing_name,regexes_partial[i,find_this]),replace_with:=str_replace(standardizing_name,regexes_partial[i,find_this],regexes_partial[i,replace_with])]
  merged[str_detect(standardizing_name,regexes_partial[i,find_this]),type:="regex_partial"]
  merged[!is.na(replace_with),standardizing_name:=replace_with]
  merged[,standardizing_name:=trimws(standardizing_name)]
}


merged[str_detect(standardizing_name,"\\'$"),standardizing_name:=str_replace(standardizing_name,"\\'$","")]
merged[str_detect(standardizing_name,"\\.$"),standardizing_name:=str_replace(standardizing_name,"\\.$","")]
merged[str_detect(standardizing_name,"^\\("),standardizing_name:=str_replace(standardizing_name,"^\\(","")]
merged[str_detect(standardizing_name,"\\)$"),standardizing_name:=str_replace(standardizing_name,"\\)$","")]
merged[standardizing_name=="",standardizing_name:="s.n"]

merged[,n_types:=.N,standardizing_name]#[N>1][,sum(N)]
merged[,n_sum:=sum(n_works),standardizing_name]
merged[n_sum>100,big_pub2:=n_sum>100,standardizing_name]

# kui mitu reeglit korra kehtib siis praegu j채채b alles ainult viimane. saaks kontrollida sellega, et juhul kui 체htki asendust veel ei ole, siis kasutada originaali. kui aga asendus juba on, siis teha selle peal.


#12910 types simplified.

merged[!str_detect(standardizing_name,"\\p{Cyrillic}"),uniqueN(publisher_unlist)]
merged[!str_detect(standardizing_name,"\\p{Cyrillic}"),uniqueN(standardizing_name)]
merged[!str_detect(standardizing_name,"\\p{Cyrillic}"),.N,standardizing_name][N>1][,sum(N)]
#2000 > 10 times
merged[big_pub==T]
merged[,count_standardized:=.N,.(standardizing_name,place_harmonized)]
merged[,standardizing_name:=substr(standardizing_name,0,50)]
merged[,publisher_unlist:=substr(publisher_unlist,0,50)]


fwrite(merged[order(place_harmonized,standardizing_name)],"data/all_publishers6.tsv",sep="\t")


```
