import re

PATTERN_245n = r"(?:([Nn]r\.?\s)|Album\s|Triloogia\s|Part\s|Heft\s|Том\s|[Tt]h?eil\s|[Кк]нига\s|[Чч]асть\s)?(?P<n>(?P<araabia>\d{1,2})|(?P<rooma>\b(?=[MDCLXVI]+\b)(M{0,4}(CM|CD|D?C{0,3})(XC|XL|L?X{0,3})(IX|IV|V?I{0,3}))\b)|(?P<arvsna>(?P<a1>([Ee]{1,2}[sd]{1,2}i?m[eaä]n{1,2}e)|([Ee]rst[ers]?)|([Ff]irst|[Oo]ne)|([Pp]remi[èe]re?)|([Пп]ерв(ый|ая|ое)))|(?P<a2>([Tt][eõö]ine)|([Zz]we[iy]t[ers]?)|([Ss]econd|[Tt]wo)|([Dd]euxi[èe]me)|([Вв]тор(ой|ая|ое)))|(?P<a3>([Kk]olmas)|([Dd]ritt[ers]?)|([Tt]hird|[Tt]hree)|([Tt]roi[sx]i[èe]me)|([Тт]рет(ий|ья|ье)))|(?P<a4>([Nn]eljas)|([Vv]iert[ers]?)|([Ff]our(th)?|[Ff]our)|([Cc]inqui[eè]me)|([Чч]етв[её]рт(ый|ая|ое)))|(?P<a5>([VWvw]i{1,2}es)|([Ff]ünft[ers]?)|([Ff]ifth|[Ff]ive)|([Cc]inqui[eè]me)|([Пп]ят(ый|ая|ое)))|(?P<a6>([Kk]u{1,2}es)|([Ss]echst[ers]?)|([Ss]ix(th)?|[Ss]ix)|([Ss]ixi[èe]me)|([Шш]ест(ой|ая|ое)))|(?P<a7>([Ss]eitsmes)|([Ss]iebt[ers]?)|([Ss]even(th)?|[Ss]even)|([Ss]epti[èe]me)|([Сс]едьм(ой|ая|ое)))|(?P<a8>([Kk]ah{1,2}eksas)|([Aa]cht[ers]?)|([Ee]ight(th)?|[Ee]ight)|([Hh]uiti[èe]me)|([Вв]осьм(ой|ая|ое)))|(?P<a9>([Üü]h{1,2}eksas)|([Nn]eunt[ers]?)|([Nn]ine(th)?|[Nn]ine)|([Nn]euvi[èe]me)|([Дд]евят(ый|ая|ое)))|(?P<a11>([Üü](ks|he)teist)|(?P<a12>[Kk]a(ks|he)teist))?(?P<a10>([Kk]ümnes)|([Zz]ehnt[ers]?)|([Tt]en(th)?|[Tt]en)|([Dd]ixi[èe]me)|([Дд]есят(ый|ая|ое))))|(?P<AB>A|B))(\.)?\s?(?P<p>(?:\[?)([A-Za-zА-Яа-яöõäüéè]+)(?:\.?\]?))?"
PATTERN_250a = r"(?P<n>(?P<araabia>\[?\d{1,2}\]?(\.|-о?[еe]|nd|rd|th|),?)|(?P<arvsna>(?P<a1>([Ee]simene)|[Ff]irst|[Ee]rste[rs]?)|(?P<a2>[Tt]eine|[Zz]weite[rs]?|[Ss]econd)|(?P<a3>[Kk]olma[ts]|[Tt]hird|[Dd]ritte[rs]?)|(?P<a4>[Nn]elja[st]|[Ff]ourth|[Vv]ierte[rs]?)|(?P<a5>[Vv]iies|[Ff]ifth|[Ff]üfte[rs]?)|(?P<a6>[Kk]uues|[Ss]ixth|[Ss]echste[rs]?)|(?P<a7>[Ss]eitsme[st]|[Ss]eventh|[Ss]iebte[rs]?)|(?P<a8>[Kk]ahh?eksa(s|mat)|[Ee]ighth?|[Aa]chte[rs]?)|(?P<a9>[Üü]hh?eksa(s|mat)|[Nn]inth|[Nn]eunte[rs]?)|(?P<a10>[Kk]ümne(s|mat)|[Tt]enth|[Zz]enthe[rs]?)))?,?\s?(?:(([Tt]äiend|[Pp]arand|[Uu]uend|[Aa]jakohast)(atud)?|[Üü]mbert(ööt(atud)?)?|[Mm]uutm(ata)?|[Mm]uud(et(ud)?)?|[Vv]erb|Повтор(ное|\.)|доп\.|[Rr]ev|[Vv]erm|[Vv]erbesserte)\.?(\sja\s(täiend|parand))?\.?\s)?(?P<tr>([Ee]sma|[Ee]ri|[Ää]ra|[Uu]us|[Kk]ordus|[Üü]mber|[Ff]aksiimile|[Pp]re|[Rr]e|[Ss]onder)?(tr(ükk|yck)?|vä?lj(aanne)?|([Aa]b)?dr(uck)?|Aufl(age)?|ed(ition)?|print|vers(i?ion)?|uppl|pain(os)?|изд))?"
PATTERN_260c = re.compile(r"(?:c|(?P<copyright>©)|tsens(eeritud|\.)\s*)?((?P<year>\d{4})(?:\.0)?(?:\?)?|(?P<decade>\d{3}-\?)|(?P<century>\d{2}--\?))")
PATTERN_300a = re.compile(r"(([IVXL]+,?\s)|(1\s(voldik|võrgu(väljaanne|ressurss))\s\())?(?P<vahemik>(?:[Ll]k\.?\s)?\d{1,4}\-\d{1,4})?(?P<arv>\b\d{1,4})?,?(\s*)?(?P<sulud>\[\d+\])?\s*(?P<uhik>lk|l\b|(nummerdamata\s)?lehte|lehekülge?|voldik|CD-ROM|(võrgu(väljaanne|ressurss)|e-raamat))?")
PATTERN_533d = re.compile(r"^(\d{4}(-\d{4})?)(\;\s\d{4}(-\d{4})?)*")
PATTERN_534c = re.compile("((?P<place>([A-ZÕÄÖÜ]\w+|[А-Я][а-я]+)(\s\;\s[A-ZÕÄÖÜ]\w+)?)?(\s?\:\s((?P<publisher>((([A-Z&]+\s)?[A-ZÕÄÖÜk]\w+(\s|\-)?)+)|(s\.\s?n\.)|((([A-ZÕÄÖÜ]|[А-Я])\.\s)+([A-ZÕÄÖÜ]\w+|[А-Я][а-я]+)))))?)?(,\s)?c?(?:([IVXLCDM]+\s)+)?((?P<range>\d{4}\-\d{4})|(?P<year>\d{4}))?")

MAPPING_375a = {'mees': 'mees',
                'naine': 'naine',
                'male': 'mees',
                'Males': 'mees',
                'Females': 'naine',
                'female': 'naine',
                'Women': 'naine',
                'Men': 'mees',
                'males': 'mees',
                'Male': 'mees',
                'sugu': None,
                'Female': 'naine',
                'females': 'naine',
                'male; Males': 'mees',
                'men': 'mees',
                'eng': None,
                'ajaloolane': None,
                'Females; naine': 'naine',
                'Non-binary people': 'non-binary',
                'meed': 'mees',
                'kirjanik': None,
                'Males; Armenians': 'mees',
                'not known': None,
                ' mees': 'mees',
                'mee': 'mees',
                '2': None,
                'Authors; Males': 'mees',
                'women': 'naine',
                'saksa': None,
                'Transgender people; Males; Transgender men': 'non-binary',
                'mees; male': 'mees',
                'fre': None,
                'kunstnik': None,
                'Women; naine': 'naine',
                'põlisrahvaste uurija': None,
                'Males; Males': 'mees',
                'tõlkija': None,
                'male; Architects': 'mees',
                'vene': None,
                'Males; eng': 'mees',
                'Males $2 lcdgt; Females': None,
                'mees0': 'mees',
                'naine; female': 'naine',
                'majandusteadlane': None,
                'filosoofiadoktor': None,
                'rus': None,
                'Males; Fantasy fiction; Authors': 'mees',
                'lit': None,
                'transgender woman; male; female': 'non-binary',
                'Music teachers; Males': 'mees',
                'persoon; mees': 'male',
                'Tokyo, Jaapan; mees': 'mees',
                'õppejõud; mees': 'mees',
                'professor': None,
                'mwwa': 'mees',
                'male; Men': 'mees',
                'Law teachers': None,
                'Femles': 'naine',
                'nane': 'naine',
                'lcdgt': None,
                'female; Women': 'naine',
                'persoon; Males': 'mees',
                'Composition teachers (Music); Females': 'naine',
                'mees; mees': 'mees',
                'mes': 'mees',
                'mess': 'mees',
                'aine': 'naine'}